# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meu_servico.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11meu_servico.proto\x12\x0bmeu_servico"\x1c\n\x08Resposta\x12\x10\n\x08resposta\x18\x01 \x01(\t"\x17\n\x06Imagem\x12\r\n\x05image\x18\x01 \x01(\x0c"1\n\x0fMinhaRequisicao\x12\x0e\n\x06\x63\x61mpo1\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61mpo2\x18\x02 \x01(\x05""\n\rMinhaResposta\x12\x11\n\tresultado\x18\x01 \x01(\t"A\n\x16OrdemServicoRequisicao\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05local\x18\x03 \x01(\t"G\n\x10OrdemServicoList\x12\x33\n\x10ordemServicoList\x18\x01 \x03(\x0b\x32\x19.meu_servico.OrdemServico"\x83\x01\n\x0cOrdemServico\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07geojson\x18\x03 \x01(\t\x12\x0b\n\x03lat\x18\x04 \x01(\x01\x12\x0b\n\x03lng\x18\x05 \x01(\x01\x12\x0f\n\x07relator\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\x08\x32\xe5\x01\n\nMeuServico\x12\x45\n\tMeuMetodo\x12\x1c.meu_servico.MinhaRequisicao\x1a\x1a.meu_servico.MinhaResposta\x12X\n\x12MetodoOrdemServico\x12#.meu_servico.OrdemServicoRequisicao\x1a\x1d.meu_servico.OrdemServicoList\x12\x36\n\x08getImage\x12\x13.meu_servico.Imagem\x1a\x15.meu_servico.Respostab\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "meu_servico_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_RESPOSTA"]._serialized_start = 34
    _globals["_RESPOSTA"]._serialized_end = 62
    _globals["_IMAGEM"]._serialized_start = 64
    _globals["_IMAGEM"]._serialized_end = 87
    _globals["_MINHAREQUISICAO"]._serialized_start = 89
    _globals["_MINHAREQUISICAO"]._serialized_end = 138
    _globals["_MINHARESPOSTA"]._serialized_start = 140
    _globals["_MINHARESPOSTA"]._serialized_end = 174
    _globals["_ORDEMSERVICOREQUISICAO"]._serialized_start = 176
    _globals["_ORDEMSERVICOREQUISICAO"]._serialized_end = 241
    _globals["_ORDEMSERVICOLIST"]._serialized_start = 243
    _globals["_ORDEMSERVICOLIST"]._serialized_end = 314
    _globals["_ORDEMSERVICO"]._serialized_start = 317
    _globals["_ORDEMSERVICO"]._serialized_end = 448
    _globals["_MEUSERVICO"]._serialized_start = 451
    _globals["_MEUSERVICO"]._serialized_end = 680
# @@protoc_insertion_point(module_scope)
